import { CompanySettings, Driver, Expense, ExpenseType, Invoice, Truck } from './types.ts';

export const EXPENSE_TYPES: ExpenseType[] = [
  'Driver Food',
  'Mobile',
  'Fuel',
  'Maintenance',
  'Tyre',
  'Washing',
  'Overtime',
  'Other',
];

export const EXPENSE_COLORS: Record<ExpenseType, string> = {
  'Driver Food': '#F59E0B', // Amber
  Mobile: '#06B6D4', // Cyan
  Fuel: '#10B981', // Emerald
  Maintenance: '#3B82F6', // Blue
  Tyre: '#EF4444', // Red
  Washing: '#8B5CF6', // Purple
  Overtime: '#EC4899', // Pink
  Other: '#6B7280', // Gray
};

export const DEFAULT_SETTINGS: CompanySettings = {
  companyName: 'Al-Sahra Heavy Equipment & Boom Trucks Co.',
  companyNameAr: 'شركة الصحراء للمعدات الثقيلة والرافعات',
  currency: 'SAR',
  defaultDailyFood: 25,
  defaultMonthlyMobile: 120,
  language: 'en',
};

export const INITIAL_TRUCKS: Truck[] = [
  {
    id: 'trk-1',
    truckNumber: 'BT-01',
    plateNumber: '4512 KSA',
    driverName: 'Ahmed Al-Ghamdi',
    ownershipType: 'Shared',
    ownerName: 'Sheikh Fahad Al-Otaibi',
    sharePercent: 40,
    status: 'Active',
    notes: '15-Ton Telescopic Boom Crane (Isuzu FVR)',
  },
  {
    id: 'trk-2',
    truckNumber: 'BT-02',
    plateNumber: '8831 KSA',
    driverName: 'Tariq Mahmoud',
    ownershipType: 'Company',
    ownerName: 'Company 100%',
    sharePercent: 0,
    status: 'Active',
    notes: '25-Ton Knuckle Boom Crane (Mercedes Actros)',
  },
  {
    id: 'trk-3',
    truckNumber: 'BT-03',
    plateNumber: '3190 KSA',
    driverName: 'Bilal Khan',
    ownershipType: 'Shared',
    ownerName: 'Khalid Al-Mutairi',
    sharePercent: 50,
    status: 'Maintenance',
    notes: '10-Ton Crane Truck (Hino 500) - Hydraulic pump service',
  },
  {
    id: 'trk-4',
    truckNumber: 'BT-04',
    plateNumber: '7724 KSA',
    driverName: 'Salem Al-Dosari',
    ownershipType: 'Company',
    ownerName: 'Company 100%',
    sharePercent: 0,
    status: 'Active',
    notes: '20-Ton Heavy Boom Truck (MAN TGS 6x4)',
  },
  {
    id: 'trk-5',
    truckNumber: 'BT-05',
    plateNumber: '9102 KSA',
    driverName: 'Mohammad Farooq',
    ownershipType: 'Shared',
    ownerName: 'Nasser Al-Qahtani',
    sharePercent: 35,
    status: 'Active',
    notes: '30-Ton Super Boom Truck (Volvo FMX)',
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'drv-1',
    name: 'Ahmed Al-Ghamdi',
    phone: '+966 50 111 2233',
    iqamaNumber: '2390184711',
    assignedTruck: 'BT-01',
    monthlySalary: 4500,
    dailyFoodAllowance: 25,
    monthlyMobileAllowance: 120,
    overtimeRate: 20,
    status: 'Active',
    notes: 'Certified Aramco heavy lift operator',
  },
  {
    id: 'drv-2',
    name: 'Tariq Mahmoud',
    phone: '+966 54 222 3344',
    iqamaNumber: '2419082314',
    assignedTruck: 'BT-02',
    monthlySalary: 4200,
    dailyFoodAllowance: 25,
    monthlyMobileAllowance: 120,
    overtimeRate: 22,
    status: 'Active',
    notes: 'Specialist in knuckle boom precision lifts',
  },
  {
    id: 'drv-3',
    name: 'Bilal Khan',
    phone: '+966 56 333 4455',
    iqamaNumber: '2381920394',
    assignedTruck: 'BT-03',
    monthlySalary: 3800,
    dailyFoodAllowance: 25,
    monthlyMobileAllowance: 120,
    overtimeRate: 20,
    status: 'Active',
    notes: 'Experienced on rough terrain construction sites',
  },
  {
    id: 'drv-4',
    name: 'Salem Al-Dosari',
    phone: '+966 55 444 5566',
    iqamaNumber: '2490182390',
    assignedTruck: 'BT-04',
    monthlySalary: 4000,
    dailyFoodAllowance: 25,
    monthlyMobileAllowance: 120,
    overtimeRate: 25,
    status: 'Active',
    notes: 'Civil infrastructure hoisting lead',
  },
  {
    id: 'drv-5',
    name: 'Mohammad Farooq',
    phone: '+966 59 555 6677',
    iqamaNumber: '2349018274',
    assignedTruck: 'BT-05',
    monthlySalary: 3900,
    dailyFoodAllowance: 25,
    monthlyMobileAllowance: 120,
    overtimeRate: 20,
    status: 'Active',
    notes: 'Long reach telescopic operations specialist',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1001',
    invoiceNumber: '#1001',
    date: '2026-09-08',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    customerName: 'Diriyah Gate Development Authority',
    jobDescription: 'Erection of timber canopy trusses - Gate 4',
    amount: 12500,
    status: 'Paid',
    notes: 'Direct transfer to corporate bank account',
  },
  {
    id: 'inv-1002',
    invoiceNumber: '#1002',
    date: '2026-09-12',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    customerName: 'ABC Contracting Co.',
    jobDescription: 'Precast concrete slab hoisting & placement',
    amount: 7500,
    status: 'Paid',
    notes: 'Site work completed and signed off',
  },
  {
    id: 'inv-1003',
    invoiceNumber: '#1003',
    date: '2026-09-15',
    truckNumber: 'BT-02',
    driverName: 'Tariq Mahmoud',
    customerName: 'Riyadh Metro Fast Consortium',
    jobDescription: 'Electrical transformer substation positioning',
    amount: 18000,
    status: 'Paid',
    notes: 'Weekend night shift crane job',
  },
  {
    id: 'inv-1004',
    invoiceNumber: '#1004',
    date: '2026-09-18',
    truckNumber: 'BT-02',
    driverName: 'Tariq Mahmoud',
    customerName: 'Al-Bawani General Contracting',
    jobDescription: 'Air conditioning chiller unit lifting to rooftop',
    amount: 6000,
    status: 'Pending',
    notes: '30-day payment term invoice',
  },
  {
    id: 'inv-1005',
    invoiceNumber: '#1005',
    date: '2026-09-20',
    truckNumber: 'BT-03',
    driverName: 'Bilal Khan',
    customerName: 'Saudi Binladin Group',
    jobDescription: 'Scaffolding pipe bundles loading and transport',
    amount: 5500,
    status: 'Paid',
    notes: 'Cheque received',
  },
  {
    id: 'inv-1006',
    invoiceNumber: '#1006',
    date: '2026-09-22',
    truckNumber: 'BT-04',
    driverName: 'Salem Al-Dosari',
    customerName: 'Qiddiya Investment Co.',
    jobDescription: 'Roller coaster structural framework crane hoist',
    amount: 22000,
    status: 'Pending',
    notes: 'Approved work order pending finance dispatch',
  },
  {
    id: 'inv-1007',
    invoiceNumber: '#1007',
    date: '2026-09-24',
    truckNumber: 'BT-05',
    driverName: 'Mohammad Farooq',
    customerName: 'Red Sea Global Logistics',
    jobDescription: 'Prefabricated eco-villa component unloading',
    amount: 28000,
    status: 'Paid',
    notes: 'Full payment cleared via SARIE',
  },
  {
    id: 'inv-1008',
    invoiceNumber: '#1008',
    date: '2026-09-25',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    customerName: 'Nesma & Partners',
    jobDescription: 'Emergency pipeline valve crane support',
    amount: 4500,
    status: 'Pending',
    notes: 'Urgent weekend callout',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    date: '2026-09-09',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    expenseType: 'Fuel',
    amount: 850,
    description: 'Diesel Euro 5 full tank - SASCO Al-Malaz Station',
    notes: 'Receipt attached #8812',
  },
  {
    id: 'exp-2',
    date: '2026-09-10',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    expenseType: 'Driver Food',
    amount: 25,
    description: 'Daily Food Allowance',
    notes: 'Recorded via quick action',
  },
  {
    id: 'exp-3',
    date: '2026-09-11',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    expenseType: 'Mobile',
    amount: 120,
    description: 'Monthly Driver Mobile & Data Allowance',
    notes: 'STC site communication',
  },
  {
    id: 'exp-4',
    date: '2026-09-13',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    expenseType: 'Maintenance',
    amount: 1800,
    description: 'Boom extension hydraulic cylinder seal replacement & grease',
    notes: 'Al-Bawardi Workshop',
  },
  {
    id: 'exp-5',
    date: '2026-09-14',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    expenseType: 'Overtime',
    amount: 200,
    description: '10 hours night shift crane lifting (20 SAR/hr)',
    notes: 'Approved by site engineer',
  },
  {
    id: 'exp-6',
    date: '2026-09-15',
    truckNumber: 'BT-02',
    driverName: 'Tariq Mahmoud',
    expenseType: 'Fuel',
    amount: 920,
    description: 'Diesel full tank - Petromin Ring Road',
  },
  {
    id: 'exp-7',
    date: '2026-09-16',
    truckNumber: 'BT-02',
    driverName: 'Tariq Mahmoud',
    expenseType: 'Tyre',
    amount: 2400,
    description: 'Two front steering Bridgestone tyres replacement',
    notes: 'Heavy duty load rating',
  },
  {
    id: 'exp-8',
    date: '2026-09-17',
    truckNumber: 'BT-03',
    driverName: 'Bilal Khan',
    expenseType: 'Maintenance',
    amount: 3200,
    description: 'Hydraulic pump overhaul & PTO spline renewal',
    notes: 'Currently in workshop',
  },
  {
    id: 'exp-9',
    date: '2026-09-18',
    truckNumber: 'BT-04',
    driverName: 'Salem Al-Dosari',
    expenseType: 'Fuel',
    amount: 880,
    description: 'Diesel refill for Qiddiya transit',
  },
  {
    id: 'exp-10',
    date: '2026-09-19',
    truckNumber: 'BT-04',
    driverName: 'Salem Al-Dosari',
    expenseType: 'Washing',
    amount: 120,
    description: 'Chassis high-pressure degrease wash',
  },
  {
    id: 'exp-11',
    date: '2026-09-20',
    truckNumber: 'BT-05',
    driverName: 'Mohammad Farooq',
    expenseType: 'Fuel',
    amount: 1400,
    description: 'Double tank diesel refill for Red Sea coastal run',
  },
  {
    id: 'exp-12',
    date: '2026-09-21',
    truckNumber: 'BT-05',
    driverName: 'Mohammad Farooq',
    expenseType: 'Other',
    amount: 350,
    description: 'SASO / TUV 3rd-party crane annual load test sticker renewal',
  },
  {
    id: 'exp-13',
    date: '2026-09-22',
    truckNumber: 'BT-01',
    driverName: 'Ahmed Al-Ghamdi',
    expenseType: 'Fuel',
    amount: 800,
    description: 'Mid-week diesel top-up',
  },
  {
    id: 'exp-14',
    date: '2026-09-23',
    truckNumber: 'BT-02',
    driverName: 'Tariq Mahmoud',
    expenseType: 'Driver Food',
    amount: 25,
    description: 'Daily Food Allowance',
  },
];
